### ISSUE TITLE
[bug] Can't set `nested_separator` to `"_"`

### ISSUE THREAD

**Issue by CXwudi** [dynaconf/dynaconf#1169]
**Describe the bug**

**To Reproduce**
First, I have the env var like following:
```
APP_FOO_BAR=some_value
```

Write a code with 

``` python
Dynaconf(
        envvar_prefix='APP',
        # environments=True,
        root_path=os.getcwd(),
        settings_files=['config.base.yaml', 'config.yaml'],
        merge_enabled=True,
        nested_separator="_",
    )
```

And put an empty `config.base.yaml` file in the current directory of the shell

Then run the python code above and observe:

```
Traceback (most recent call last):
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 800, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'qbittorrent-add-trackers.component.qbittorrent_client.QbittorrentClient'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 800, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'qbittorrentapi.client.Client'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workspace/qbittorrent-add-trackers/qbittorrent-add-trackers/main.py", line 16, in main
    client = injector.get(QbittorrentClient)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 976, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 802, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 813, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 1041, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 1089, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 976, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 802, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 813, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/injector/__init__.py", line 1050, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/qbittorrent-add-trackers/component/di_module.py", line 12, in qbittorrent_client
    return Client(config.qbittorrent.url, config.qbittorrent.username, config.qbittorrent.password)
                  ^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/dynaconf/base.py", line 122, in __getattr__
    self._setup()
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/dynaconf/base.py", line 183, in _setup
    self._wrapped = self._wrapper_class(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/dynaconf/base.py", line 273, in __init__
    self.execute_loaders()
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/dynaconf/base.py", line 1185, in execute_loaders
    core_loader.load(self, env, silent=silent, key=key)
  File "/workspace/qbittorrent-add-trackers/.venv/lib/python3.12/site-packages/dynaconf/loaders/env_loader.py", line 27, in load
    if global_prefix is False or global_prefix.upper() != "DYNACONF":
                                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'
```

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

.
├── README.md
├── config.base.yaml
├── config.yaml
├── poetry.lock
├── pyproject.toml
├── qbittorrent-add-trackers
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-312.pyc
│   │   └── main.cpython-312.pyc
│   ├── component
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-312.pyc
│   │   │   ├── di_module.cpython-312.pyc
│   │   │   └── qbittorrent_client.cpython-312.pyc
│   │   ├── di_module.py
│   │   └── qbittorrent_client.py
│   ├── config
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-312.pyc
│   │   │   ├── config.cpython-312.pyc
│   │   │   └── di_module.cpython-312.pyc
│   │   ├── config.py
│   │   └── di_module.py
│   ├── di_container.py
│   └── main.py
└── tests
    └── __init__.py
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**./config.base.yaml**
```yaml
qbittorrent:
  url: 
  username: 'admin'
  password: 

trackers:
  urls: ['https://cf.trackerslist.com/all.txt']

redis:
  host: 'redis'
  port: 6379
  password:


logging:
  level: 'INFO'
```

and

**./config.yaml**
```yaml
# empty so far
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**./qbittorrent-add-trackers/config/config.py**
```python
import os
from dynaconf import Dynaconf


def load_config():
    return Dynaconf(
        envvar_prefix='APP',
        # environments=True,
        root_path=os.getcwd(),
        settings_files=['config.base.yaml', 'config.yaml'],
        merge_enabled=True,
        nested_separator="_",
    )


```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
poetry shell
poetry install
poetry run main
```

where the poetry file is:

``` toml
[tool.poetry]
name = "qbittorrent-add-trackers"
version = "0.1.0"
description = ""
authors = ["CXwudi <cx2010017@gmail.com>"]
readme = "README.md"
packages = [{ include = "qbittorrent-add-trackers" }]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
qbittorrent-api = "^2024.7.64"
logging = "^0.4.9.6"
websocket-client = "^1.8.0"
injector = "^0.22.0"
dynaconf = "^3.2.6"

[tool.poetry.scripts]
main = "qbittorrent-add-trackers.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

</details>

**Expected behavior**
Env var like with only one dash like "APP_FOO_BAR" should be parsed correctly when setting `nested_separator` to `"_"`

**Environment (please complete the following information):**
 - OS: Debian 12 in devcontainer
 - Dynaconf Version: 3.2.6
 - Frameworks in use: only injector

**Additional context**

**Comment by rochacbruno** [comment]
Well, I think this is unsolvable.

We can't have `nested_separator` set to `_`, because this conflicts with reading any variable that contains `_` and we have many.

When the loader tries to read `settings.get("ENVVAR_PREFIX")` what it ends up doing is trying to lookup `ENVVAR` and then `PREFIX` because it used the `_` to separate the lookup key passed to  `get` method.

It would be ambiguous to allow the nested separator to be a single underscore, the only way would be allowing only variables without `_` in it or having a schema (which is coming in 4.0)

For now we can assume this is not possible.

**Comment by CXwudi** [comment]
I see, this is really hard to solve. I understand that changing the design is a huge effort. Likewise, I don't mind if this issue is marked as won't fix.

Anyway, thanks for your explanation

**Comment by rochacbruno** [comment]
@CXwudi With the new schema, we will be able to disambiguate on those cases, however the timeline for 4.0 with the schema support will be for the end of year.

https://github.com/dynaconf/dynaconf/labels/typed_dynaconf
