### ISSUE TITLE
[bug] settings.setenv Fails With UnicodeDecodeError

### ISSUE THREAD

**Issue by OmmarShaikh01** [dynaconf/dynaconf#770]
**Code Repository** [Apollo](https://github.com/OmmarShaikh01/Apollo/tree/dev)

**Describe the bug**
Running an executable built by pyinstaller dynaconf raises UnicodeDecodeError

**Dynaconf Initlization**
```py
settings = Dynaconf(
    load_dotenv=False,
    project_root=os.path.dirname(ROOT),
    settings_files=[
        os.path.join(ROOT, "default_settings.toml"),
        os.path.join(ROOT, "default_testing_settings.toml"),
        os.path.join(ROOT, "default_qt_testing_settings.toml"),
        os.path.join(ROOT, "settings.toml"),
        os.path.join(ROOT, "testing_settings.toml"),
        os.path.join(ROOT, "qt_testing_settings.toml"),
    ],
    envvar_prefix="DYNACONF",
    environments=True,
    env_switcher="ENV_FOR_DYNACONF",
    validate_only_current_env=True,
    dynaconf_skip_loaders=False,
    validators=validate(),
)
```

**Error Traceback**
```
Traceback (most recent call last):
  File "apollo\__main__.py", line 18, in <module>
    settings.setenv("PRODUCTION")
  File "D:\Dev\Apollo\dist\Apollo-0.1.0\.venv\lib\site-packages\dynaconf\base.py", line 113, in __getattr__
    self._setup()
  File "D:\Dev\Apollo\dist\Apollo-0.1.0\.venv\lib\site-packages\dynaconf\base.py", line 172, in _setup
    self._wrapped = Settings(
  File "D:\Dev\Apollo\dist\Apollo-0.1.0\.venv\lib\site-packages\dynaconf\base.py", line 251, in __init__
    self.execute_loaders()
  File "D:\Dev\Apollo\dist\Apollo-0.1.0\.venv\lib\site-packages\dynaconf\base.py", line 1035, in execute_loaders
    execute_hooks("post", self, env, silent=silent, key=key)
  File "D:\Dev\Apollo\dist\Apollo-0.1.0\.venv\lib\site-packages\dynaconf\loaders\__init__.py", line 121, in execute_hooks
    hook_module = py_loader.import_from_filename(
  File "D:\Dev\Apollo\dist\Apollo-0.1.0\.venv\lib\site-packages\dynaconf\loaders\py_loader.py", line 90, in import_from_filename
    if filename in [item.filename for item in inspect.stack()]:
  File "D:\Programs\Python39\lib\inspect.py", line 1554, in stack
    return getouterframes(sys._getframe(1), context)
  File "D:\Programs\Python39\lib\inspect.py", line 1531, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "D:\Programs\Python39\lib\inspect.py", line 1505, in getframeinfo
    lines, lnum = findsource(frame)
  File "D:\Programs\Python39\lib\inspect.py", line 833, in findsource
    lines = linecache.getlines(file)
  File "linecache.py", line 46, in getlines
  File "linecache.py", line 137, in updatecache
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 9: invalid continuation byte
```

**To Reproduce**
1. Install poetry to manage the environment
2. Build the application package using .\tools\build.ps1 -format frozen-zip
3. execute Apollo.exe generated in .\dist\build\Apollo

**Expected behavior**
Apollo.exe Should Launch the mainwindow.

**Environment (please complete the following information):**
 - OS: Windows/10
 - Dynaconf Version ^3.1.8
 - Frameworks in use Qt

**Comment by OmmarShaikh01** [comment]
Pyinstaller Compiles the Dynaconf Modules and loaders so when _dynaconf.loader.py_loader_ tries to load files from the inspect stack trace it tries to read compiled pyc files and fails on UnicodeDecodeError. The fix is to pacakage dynaconf and python-dotenv[cli] as a package without compiling it by using the **--collect-all** argument of pyinstaller
