### ISSUE TITLE
[bug] order of the env variables breaks parsing

### ISSUE THREAD

**Issue by AmadiL** [dynaconf/dynaconf#869]
**Describe the bug**
If dynamic env variables are in the wrong order, and depend on each other (eg. in the `.env` file) the config will not parse.
This is problematic in docker environment because the order of env variables might be random.
The problem didn't occur when I deleted `config-defaults.yaml` from the example or `@format` was used in place of `@jinja`.

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

.
├── Dockerfile
├── config-defaults.yaml
├── config.py
└── requirements.txt

1 directory, 4 files

```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**.env**
```bash
APP_PATH_ROOT=@jinja {{this.PATH_ROOT_REL | abspath}}
APP_PATH_DATA=@format {this.PATH_ROOT}/some_data
APP_PATH_ROOT_REL=..
APP_PATH_MODEL=@format {this.PATH_ROOT}/some_model
```

and

**config-defaults.yaml**
```yaml
PATH_ROOT: ../..
PATH_DATA: "@jinja {{this.PATH_ROOT | abspath}}/data"
PATH_MODEL: "@jinja {{this.PATH_ROOT | abspath}}/models"
PATH_CONFIG: "@jinja {{this.PATH_ROOT | abspath}}/config"
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/config.py**
```python
from pathlib import Path

from dynaconf import Dynaconf
from pprint import pprint

src_dir = Path(__file__).parent.resolve()

settings = Dynaconf(
    envvar_prefix="APP",
    settings_files=["config.yaml", src_dir / "config-defaults.yaml"],
    load_dotenv=True,
    merge_enabled=True,
)

pprint(settings.as_dict())
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ python config.py
Traceback (most recent call last):
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/config.py", line 15, in <module>
    pprint(settings.as_dict())
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 115, in __getattr__
    self._setup()
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 174, in _setup
    self._wrapped = Settings(
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 253, in __init__
    self.execute_loaders()
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 1035, in execute_loaders
    core_loader.load(self, env, silent=silent, key=key)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/loaders/env_loader.py", line 24, in load
    load_from_env(obj, global_prefix, key, silent, IDENTIFIER + "_global")
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/loaders/env_loader.py", line 82, in load_from_env
    obj.update(data, loader_identifier=identifier)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 952, in update
    self.set(
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 869, in set
    existing = getattr(self, key, None)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 298, in __getattribute__
    return self._store[name]
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/boxing.py", line 26, in evaluate
    return recursively_evaluate_lazy_format(value, settings)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/__init__.py", line 413, in recursively_evaluate_lazy_format
    value = value(settings)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py", line 188, in __call__
    result = self.formatter(self.value, **self.context)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py", line 146, in __call__
    return self.function(value, **context)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py", line 157, in _jinja_formatter
    return jinja_env.from_string(value).render(**context)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/base.py", line 298, in __getattribute__
    return self._store[name]
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/boxing.py", line 26, in evaluate
    return recursively_evaluate_lazy_format(value, settings)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/__init__.py", line 413, in recursively_evaluate_lazy_format
    value = value(settings)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py", line 188, in __call__
    result = self.formatter(self.value, **self.context)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py", line 146, in __call__
    return self.function(value, **context)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/dynaconf/utils/parse_conf.py", line 157, in _jinja_formatter
    return jinja_env.from_string(value).render(**context)
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/amadeusz.lisiecki/workspace/dynaconf-test/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/Users/amadeusz.lisiecki/.pyenv/versions/3.9.14/lib/python3.9/posixpath.py", line 375, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not Undefined
```

</details>

**Expected behavior**
Environment variables can come in random order and freely depend on each other.

**Environment (please complete the following information):**
 - OS: macOS Ventura 13.1
 - Dynaconf Version 3.1.11
 - Jinja2 Version 3.1.2

**Additional context**
I faced this problem mostly in a cloud environment where I was running docerized jobs - because environment variables where passed by the job controller (sagemaker in this case). I reproduced this docker container and then locally in virtual environment. Because of this I wasn't able to use dynamic variables in my jobs.

**Comment by rochacbruno** [comment]
@pedro-psb do you think we can close this issue as resolved?

**Comment by pedro-psb** [comment]
@rochacbruno I was wanting to review this first but was busy with other things. I'll try to do it this week

**Comment by AmadiL** [comment]
Fix worked for me in multiple, previously bugged, cases - thanks for the great work!

**Comment by pedro-psb** [comment]
I've reviewed that case and we can close it now!

I'll summarize some more in-depth understanding of the original problem (as a note for the future, as it may be relevant for related issues).

### Problem breakdown

Given these dependencies loaded in this order: (b'-b and a'-a are the same keys, but from different sources)

```python
# first source A
b' -> a' # reads: b' depends on a'
a'

# second source B
a -> c
b -> a (this will break)
c
```

Internally something like this happens:

```bash
# internall calls
setting.set(b') # ok: store lazy (b')
setting.set(a') # ok: store (a')

setting.set(a) # ok: replaces lazy (a')  with lazy (a)
setting.set(b) # raises
	# check if (b) already exist (for merging purposes)
	existing = self.get(b, None)
	# it exists: lazy (b'), from source A

	# this then triggers recursive evaluation, because all Box access triggers this
	recursive_evaluation:
		resolve (b'), but
		(b') dependends on (a) # previously a'
		(a) depends on (c)
		(c) isn't set yet
```

And somehow `(a)` ends up in jinja template resolver and filter processing as `undefined`(when trying to resolve `(b')`), which raises the original exception. This is odd, as I would expect another kind of error, but this is not the critical point.
### Conclusions

My current workaround may cause some edge merging cases involving Lazy object to fail, because it just ignores the existing setting if it is of Lazy type. While it works well I think we can focus on other priorities, but if this become a problem I have the following hints:

#### Improve Box acessors

A more broad and complete solution would involve allowing a more flexible acessor to Box objects, which allow internal use to properly skip recursive evaluations. Unintentionally calling recursive evalution internally is wastefull and may cause bugs. Also, it would be nice to separate public and private `get` and `set` methods for `Settings`, as requirement for both can be very different.

I did a workaround for bypassing evaluation before, while working on other issues (setting `box._conf_box["_bypass_evaluation"]`). It kinda worked but it is not robust at all. Recently it presented some problems, due to it's kind-of-global-variable nature.

#### Improve dependency resolving

Still, it maybe be necessary to evaluate a Lazy object to check if it is mergeable (in this hypothetical merge-with-lazy edge case), so if this happens to be a real problem, I'd go for implementing a dependency analysis with `graphlib` (similar to a draft I did for `configx`), which would allow for isolating the dependent setting from a bulk loading process and, after that, set only those dependent keys in the proper order.
