### ISSUE TITLE
Add docs for PyCharm IDE Run Test Issue

### ISSUE THREAD

**Issue by rochacbruno** [dynaconf/dynaconf#880]
### Discussed in https://github.com/dynaconf/dynaconf/discussions/878

<div type='discussions-op-text'>

<sup>Originally posted by **darktempla** March  3, 2023</sup>
First and foremost I have been using Dynaconf for over a year now and really liking it so kudos to it's creator and the community for making it what it is today. 

So in summary I run into an issue where I cannot run the python tests from the IDE if I am using Dynaconf configuration. The stack trace indicates this is a dynaconf issue likely around pathing.

It is possible I have done something wrong as I have not used dynaconf much in relation to using it inside a python package you wish to bundle the dynaconf configuration inside. I also have not found any really good examples on Github that demonstrate what I am attempting to do. 

As such any help would be greatly appreciated as not being able to run from the IDE makes debugging the code painful.

More details below:

----
**Problem Overview** 

Python Version: `Python 3.10.8`
Poetry Version: `Poetry (version 1.4.0)`

The description below outlining the issue is describing the code below which can be used to replicate the issue:
https://github.com/darktempla/dynaconf-test

The dynaconf settings I want to be packaged up with the module.

As such the config and **settings.toml** and **secrets.toml** files have been moved into the package folder `dynaconf_test`. 

So in the `dynaconf_test/config.py` file I have set the root path to `root_path='./dynaconf_test/'`. 

When I run the tests from the terminal using the following command the dynaconf is picked up okay and the test passes.

```bash
poetry run python -m unittest discover -v
```

If I want to run the test from the IDE then it fails with the following error:

```commandline
/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/bin/python /Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_unittest_runner.py --target test_main.TestMain 
Testing started at 3:45 am ...
Launching unittests with arguments python -m unittest test_main.TestMain in /Users/darktempla/Code/Projects/dynaconf-test/tests



Ran 1 test in 0.015s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/Users/darktempla/Code/Projects/dynaconf-test/tests/test_main.py", line 9, in test_main
    settings.setenv('test')
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/base.py", line 115, in __getattr__
    self._setup()
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/base.py", line 174, in _setup
    self._wrapped = Settings(
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/base.py", line 253, in __init__
    self.execute_loaders()
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/base.py", line 1026, in execute_loaders
    settings_loader(
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/loaders/__init__.py", line 167, in settings_loader
    found = obj.find_file(item, project_root=p_root)
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/base.py", line 1156, in find_file
    return find_file(*args, **kwargs)
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/utils/files.py", line 63, in find_file
    search_tree.extend(_walk_to_root(project_root, break_at=work_dir))
  File "/Users/darktempla/Library/Caches/pypoetry/virtualenvs/dynaconf-test-7APtyPOS-py3.10/lib/python3.10/site-packages/dynaconf/utils/files.py", line 15, in _walk_to_root
    raise OSError("Starting path not found")
OSError: Starting path not found
```
----</div>

**Comment by pedro-psb** [comment]
Where this should go in the docs? It seems to fit under a new "Getting Help" type of page.
If so, should this be a FAQ (rewritting/summarizing the topic)?

Related to this, there could be a link to github Discussion Q&A somewhere. Maybe at the bottom of the front page (near License and More) and also in this new page, if it is created.

**Comment by rochacbruno** [comment]
I like the idea of adding a FAQ subsection
