### ISSUE TITLE
[bug] dynaconf init fails in git bash on Windows

### ISSUE THREAD

**Issue by ebundy** [dynaconf/dynaconf#931]
**Describe the bug**
On Windows, the init command works on the Windows Dos console but fails because of encoding problem on the Git Bash console.

**To Reproduce**

`dynaconf init  -f toml` 

Here the error I get with git bash:
```
$ dynaconf init  -f toml
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\dynaconf.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\dynaconf\vendor\click\core.py", line 217, in __call__
    def __call__(A,*B,**C):return A.main(*(B),**C)
  File "c:\python39\lib\site-packages\dynaconf\vendor\click\core.py", line 201, in main
    H=E.invoke(F)
  File "c:\python39\lib\site-packages\dynaconf\vendor\click\core.py", line 341, in invoke
    with C:return F(C.command.invoke(C))
  File "c:\python39\lib\site-packages\dynaconf\vendor\click\core.py", line 284, in invoke
    if A.callback is not _A:return ctx.invoke(A.callback,**ctx.params)
  File "c:\python39\lib\site-packages\dynaconf\vendor\click\core.py", line 166, in invoke
    with G:return A(*(B),**E)
  File "c:\python39\lib\site-packages\dynaconf\vendor\click\decorators.py", line 21, in A
    def A(*A,**B):return f(get_current_context(),*(A),**B)
  File "c:\python39\lib\site-packages\dynaconf\cli.py", line 271, in init
    click.echo("\u2699\ufe0f  Configuring your Dynaconf environment")
  File "c:\python39\lib\site-packages\dynaconf\vendor\click\utils.py", line 82, in echo
    if A:B.write(A)
  File "c:\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

```

**Expected behavior**
Working in both cases

**Environment :**
- OS: Windows 10 Professionnel, Version 21H2, Build : 19044.2846
- Mintty 3.6.4
- Dynaconf Version : 3.1.12

**Comment by rochacbruno** [comment]
#1163
