### ISSUE TITLE
[bug] 'dynaconf init -f ini' fails in on Windows

### ISSUE THREAD

**Issue by pieter-wsp** [dynaconf/dynaconf#936]
**Describe the bug**
On Windows, the init with ini file format fails.

**To Reproduce**

`dynaconf init -f ini`

this is the output I get:

```
⚙️  Configuring your Dynaconf environment
------------------------------------------
🐍 The file `config.py` was generated.
  on your code now use `from config import settings`.
  (you must have `config` importable in your PYTHONPATH).

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Scripts\dynaconf.exe\__main__.py", line 7, in <module>
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\vendor\click\core.py", line 217, in __call__
    def __call__(A,*B,**C):return A.main(*(B),**C)
                                  ^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\vendor\click\core.py", line 201, in main
    H=E.invoke(F)
      ^^^^^^^^^^^
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\vendor\click\core.py", line 341, in invoke
    with C:return F(C.command.invoke(C))
                    ^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\vendor\click\core.py", line 284, in invoke
    if A.callback is not _A:return ctx.invoke(A.callback,**ctx.params)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\vendor\click\core.py", line 166, in invoke
    with G:return A(*(B),**E)
                  ^^^^^^^^^^^
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\vendor\click\decorators.py", line 21, in A
    def A(*A,**B):return f(get_current_context(),*(A),**B)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\cli.py", line 383, in init
    loader.write(settings_path, settings_data, merge=True)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python311\Lib\site-packages\dynaconf\loaders\ini_loader.py", line 60, in write
    new = ConfigObj()
          ^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

in the above I replaced my output of `echo %USERPROFILE%` with `%USERPROFILE%`.

**Expected behavior**
Similar to what should be the default output for initializing for toml:
```
⚙️  Configuring your Dynaconf environment
------------------------------------------
🐍 The file `config.py` was generated.

🎛️  settings.ini created to hold your settings.

🔑 .secrets.ini created to hold your secrets.

🙈 the .secrets.* is also included in `.gitignore`
beware to not push your secrets to a public repo.

🎉 Dynaconf is configured! read more on https://dynaconf.com
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Dynaconf Version 3.1.12

**Comment by rochacbruno** [comment]
#1154 deprecation of init command

**Comment by rochacbruno** [comment]
#1163
